db:
        server: ""
        database: ""
        username: ""
        password: ""
        driver: "{ODBC Driver 17 for SQL Server}"
twitter:
        access_token: ""
        access_token_secret: ""
        consumer_key: ""
        consumer_secret: ""
